### ISSUE TITLE
Report Fields Not Saved as Default

### ISSUE THREAD

**Issue by valrdclr** [Syslifters/sysreptor#163] opened 2023-12-07 10:58 UTC
The report fields randomly stop being updated in the pdf preview (when designing the template). I have to create a new field and delete the old one. Also the old fields somehow get cached I guess and if you try to use the same id (even after deleting it), the old value still pops out in the pdf preview.

I would consider this higher priority as it can cause unwanted output which causes the output to look wrong/unprofessional as it's hard to notice if some changes weren't applied (even if it updated properly when creating the final report).

Update:
I understood whats causing the issue. When you edit the field in the "report fields" section, it is not updated in the "preview data" section, and as a result not updating in he pdf preview.

**Comment by MWedl** [comment] 2023-12-07 13:32
> When you edit the field in the "report fields" section, it is not updated in the "preview data" section, and as a result not updating in he pdf preview.

When the field definition is updated, the server also updates structure of the PDF preview data. Note that there might be problems when working with multiple browser tabs, but there should be a warning in the UI. The PDF designer initially loads the field definition via an API request. When the field definition is changed in another tab, the PDF designer does not know that and still uses the old version. Could this be the root cause of your problems?

Does force refreshing the pdf preview page in your browser resolve the out-of-sync field definition problems?

> Also the old fields somehow get cached I guess and if you try to use the same id (even after deleting it), the old value still pops out in the pdf preview.

This is intended behavior. If someone accidentally deletes a field, the content is still on the server. When you restore the field (create the deleted field again with the same ID), the old content is still there.

**Comment by valrdclr** [comment] 2023-12-07 13:47
I have a single browser tab. Basically this is my flow that leads to the bug:
1. Go to "Report Fields", edit the content of my field and press "Save"
2. Go to "PDF Designer" section and try to refresh PDF.
3. After refreshing the value doesn't change and if you go to "Preview Data" section in PDF Designer, it remains the old value. Additionally, I tried to refresh the page after saving the field value, and then going to the preview, and no luck. 

**I used:**
Google Chrome Version 120.0.6099.71 (Official Build) (64-bit)
Version 117.0.5938.149 (Official Build)  Debian kali-rolling (64-bit)

**Comment by valrdclr** [comment] 2023-12-07 14:44
> Could you check if the bug is still present in the latest version or the main branch?
> 
> > edit the content of my field
> 
> What did you edit exactly? Updating the field structure (id, type, moving fields) should also update in the PDF preview. However, changing the default value of fields will not override it in the PDF preview, because there is already a value.

Indeed. I was updating the default value fields. I thought the preview is grabbing the same values.
So basically I need to play with my values in preview and them copy them as default values? (I was doing this so far)
Maybe this part of the architecture is confusing, at least for me. Because I am expecting to design my field and save it as default value ( because later I will use the template for reports ).

**Comment by MWedl** [comment] 2023-12-07 14:55
Sorry to confuse you. This was a deliberate design decision to be able to overwrite default values in the PDF preview. For example the default value for a finding description you might have just a rough boilerplate text and some TODOs, but in the Preview data you want to test formatting with longer texts, secreenshots, etc.

Maybe we could update the PDF preview fields if field contents were not overwritten (i.e. field != default). This would automatically update unchanged fields (like in your use-case), while preserving manually overwritten field contents (no data loss).

**Comment by valrdclr** [comment] 2023-12-07 16:09
> Sorry to confuse you. This was a deliberate design decision to be able to overwrite default values in the PDF preview. For example the default value for a finding description you might have just a rough boilerplate text and some TODOs, but in the Preview data you want to test formatting with longer texts, secreenshots, etc.
> 
> Maybe we could update the PDF preview fields if field contents were not overwritten (i.e. field != default). This would automatically update unchanged fields (like in your use-case), while preserving manually overwritten field contents (no data loss).

I understood what you mean. Then maybe adding a button dropdown named "Save as default" (under the "Save" button, or near it) so that I can save the current design without using CTRL-C , CTRL-V every time I'm done with a change. This would also ensure there is always a backup in the "default" value which can be overwritten using that specific button. And maybe a popup "Are you sure you want to overwrite the current default value".
What do you think?

**Comment by MWedl** [comment] 2023-12-07 16:22
Yes that would be possible. I would prefer to have a "save as default" button per field for more granular control.

**Comment by valrdclr** [comment] 2023-12-08 07:36
> Yes that would be possible. I would prefer to have a "save as default" button per field for more granular control.

Yes. Exactly, per field. And maybe a bullet light indicator in the corner of the button or somewhere else that shows if it's already saved. (similar the one we already have on "Save" button). 

By the way, I changed the title to not confuse people as it was my mistake as I didn't understood the design here.
I think we could close the issue. Thanks for the clarifications.

**Comment by 7MinSec** [comment] 2024-01-26 16:45
What I ran into last night is the first time I populated a Report Field, I improperly called a value like `{{ start.date}}` (with a typo in the syntax), which made the report error out when generating the PDF.  

After a long time of playing with values in Report Fields, I finally realized that the Preview Data had my error in it from the *first* time I populated the info, and that's why the report would error out no matter what I changed in Report Field area.

Could there maybe be a function that copies all the current Report Fields into the Preview Data fields?

**Comment by MWedl** [comment] 2024-01-31 13:47
We implemented syncing updated default values to preview data fields (if preview data fields were not overwritten) as described in https://github.com/Syslifters/sysreptor/issues/163#issuecomment-1845492010.

Additionally we introduced two actions to markdown fields in preview data to manually sync default values:
![image](https://github.com/Syslifters/sysreptor/assets/29510012/034f131d-baee-4446-8e22-ae68f7bccf03)

The changes will be included in the next release.

**Comment by MWedl** [comment] 2024-02-14 13:07
Released in https://github.com/Syslifters/sysreptor/releases/tag/2024.13

**Closed by MWedl** 2024-02-14 13:07 UTC
Labels: enhancement, in progress
