### ISSUE TITLE
HTB CPTS Report Template Layout Issue

### ISSUE THREAD

**Issue by kmahyyg** [Syslifters/sysreptor#203] opened 2024-01-29 17:46 UTC
In 2024.8, It seems only "Flag Discovered" page when trying to publish a pdf report, may render a table with `overflow-x`.

![20240130-014010-Google Chrome-007848@2x](https://github.com/Syslifters/sysreptor/assets/16604643/6a9e7505-770e-4565-a382-10ff37da1687)

(This template is imported about a month ago, please let me know if there's a known issue.)

The expected result should be:

![20240130-014321-Google Chrome-007850@2x](https://github.com/Syslifters/sysreptor/assets/16604643/60e5e646-2416-45c5-9c8d-8233718bf32c)

I patched this by customizing the template using a workaround, but I'm not a frontend engineer, so this may be not that perfect:

```css
/* Table styling */
table, th, td {
  border: 1px solid white;

  /* WORKAROUND: Add lines below */
  word-wrap: break-word;
  table-layout: fixed;
  overflow-wrap: break-word;
}
```

**Comment by MWedl** [comment] 2024-01-30 09:02
Hi, this is a general problem of the base styles (`@import "/assets/global/base.css";` imported at the top of the CPTS design CSS) affecting all designs, not just CPTS.

I think the best solution would be to use `overflow-wrap: anywhere;`. We will add this rule to the table base styles in the next release.

**Comment by MWedl** [comment] 2024-02-14 13:10
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.13

**Closed by MWedl** 2024-02-14 13:10 UTC
Labels: in progress

**Comment by kmahyyg** [comment] 2024-09-20 04:27
Same problem exists in latest version 2024.70 in CDSA template under the `Appendix - Technical Timeline` section. (Note: The table I input into this section is not the original one, I replaced it with another additional column named "Comments", which is containing long single line)

**Comment by MWedl** [comment] 2024-09-20 05:06
I could not reproduce this behavior. Did you customize the CDSA design?

![image](https://github.com/user-attachments/assets/ef571b64-d2ee-4c0f-a721-9b5fc293cb42)

**Comment by kmahyyg** [comment] 2024-09-20 05:18
Nope, default one:

![20240920-131759-Google Chrome-009570@2x](https://github.com/user-attachments/assets/ba1494dc-0c23-46dc-bb5f-9a968623cbdf)

**Comment by kmahyyg** [comment] 2024-09-20 05:27
Reproducible content:

```
| Time  (TZ)                     | User                        | Machine | Action                                                       | Additional Comment                                           |
| ------------------------------ | --------------------------- | ------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 2222-22-22T22:22:22-00:00  | xx            | ss  | BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                   | PID 11111                                                  |
| 2222-22-22T22:22:22-00:00  | xx            | ss  | BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                       | PID 11111                                                     |
| 2222-22-22T22:22:22-00:00     2222-22-22T22:22:22-00:00     | BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                | ppp | Executed:     `pBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB` | 12345 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB |
```

**Comment by kmahyyg** [comment] 2024-09-20 05:27
If this is expected behaviour due to unpredicted long line, and you'd like to ignore this issue, please feel free to let me know.

**Comment by MWedl** [comment] 2024-09-20 06:20
Thanks for the reproduction text. It seems that inline code is the problem.

Long text inside inline code does not trigger a word break when there is not enough space left in the table. Word breaks for regular text work as expected. We will add the CSS rule `word-break: break-all;` to the base styles to force line breaks for inline code inside tables.

**Comment by kmahyyg** [comment] 2024-09-20 07:52
Hi Michael,

Thanks for such kind of great response and glad you've found the root cause, I'll wait for next release to fix it on my instance :)

thanks again for your excellent work.
