### ISSUE TITLE
[BUG] Large enum item list slows down the app considerably

### ISSUE THREAD

**Issue by danperezasensio** [Syslifters/sysreptor#149] opened 2023-11-22 15:35 UTC
When adding a finding field with type enum, for example, to import all the CWE list numbers, the application gets really slow.
The format used was:
- id: cwe_number
- value: Number

The bulk upload (3000 lines aprox. to import the 934 CWE items as JSON object) was done via intercepting the PATCH request with a proxy and adding the whole JSON object.

The result is that the loading page time takes ages.

**Comment by MWedl** [comment] 2023-11-23 16:06
I have added some server-side optimizations (cache field definition parsing, prevent fetching definitions in lists) and lazy rendering of enum choices. This will hopefully icrease performance and prevent SysReptor from slowing down too much. 

However, these are only minor improvements that do not address the root cause. The performance impact of large lists (and generally large field definitions) results from how SysReptor stores and processes these definitions. Internally, the field definition of a design is stored as a large JSON object. The field definition is needed for many operations on the server and the client (e.g. formatting data in API responses, validating data structure in API requests, displaying forms, etc.). Large lists in the definition are also loaded each time, which causes additional load and decreases performance. This was an early design decision and is not easy to change.

**Comment by MWedl** [comment] 2023-12-11 08:25
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.145

**Closed by MWedl** 2023-12-11 08:25 UTC
Labels: in progress

**Comment by aronmolnar** [comment] 2024-02-15 06:48
@danperezasensio We now implemented a dedicated CWE field type.
https://docs.sysreptor.com/designer/field-types/#cwe
