### ISSUE TITLE
PDF Character encoding problem

### ISSUE THREAD

**Issue by c3sro** [Syslifters/sysreptor#316] opened 2024-08-29 11:12 UTC
Some strings like `ff` in the final PDF file will result in e.g. `昀昀` when copied from the PDF, but are still displayed as expected as `ff`.

Steps to reproduce:
1. Enter Text in some chapter
      ```
      Test
      
      ff
      
      fi
      
      xxxffxxx
      
      xxxfixxx
      ```
      ![1](https://github.com/user-attachments/assets/dbddc60f-58d3-4f2c-8abe-c3400e3aebe7)

2. Switch to `Publish` to generate PDF (Preview display still looks good, copy + paste work as expected)
      ![2](https://github.com/user-attachments/assets/e1e8fffe-83f5-4f31-88b6-69548e3680e8)

3. Download PDF and open it in browser/PDF editor
      ![3](https://github.com/user-attachments/assets/dd30738e-88cf-4888-8f2a-45c93491433c)

Expected Result:
Text copied from the PDF is exactly the same as entered previously.

Actual Result:
Some characters don't match previously entered values.

Observed transformations:
`ff`->`昀昀`
`fi` -> `昀椀`

**Comment by MWedl** [comment] 2024-08-29 11:45
Thanks for reporting. We will investigate this.

**Comment by aronmolnar** [comment] 2024-09-03 12:10
PDFs that are displayed in the "Publish" menu are not compressed to save time. If you download the PDF, there is a postprocessing step to reduce the file size using Ghostscript.

The error that you observed is due to a [bug in Ghostscript](https://bugs.ghostscript.com/show_bug.cgi?id=706533), which was fixed in the meantime but not yet available in Debian repos (from where we currently install Ghostscript).

You can disable the postprocessing step by setting `COMPRESS_PDF=false` in your `app.env` as a workaround.

We will check what other installation options we have to resolve the bug.

**Comment by MWedl** [comment] 2024-09-24 07:44
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.74

**Closed by MWedl** 2024-09-24 07:44 UTC
Labels: in progress

**Comment by jojole-cloud** [comment] 2025-05-13 14:53
Hi I have this problem in the cloud version - is there any way to fix it? or anything I can do to my PDF after it renders?

**Comment by aronmolnar** [comment] 2025-05-13 17:48
When downloading the report, Ghostscript seems to break e.g., the letter "fi":

![Image](https://github.com/user-attachments/assets/6bec5930-2bc1-4259-bea1-fc4a586ced1e)

After copy/paste

![Image](https://github.com/user-attachments/assets/ea0f17e8-edc1-44a2-a69e-89d418d35c89)

I temporarily disabled PDF compression on labs.sysre.pt so that there are no issues with HTB reports.

**Comment by MWedl** [comment] 2025-05-14 06:56
Thanks for the bug report. The root cause is a regression for the ghostscript bug re-introduced in v10.05.0. We have reported it to the ghostscript developers: https://bugs.ghostscript.com/show_bug.cgi?id=706533#c5

Additionally, we will try to downgrade ghostscript to v10.04.0 in the docker images.

**Comment by MWedl** [comment] 2025-05-28 10:29
Pinned ghostscript to v10.04.0 in https://github.com/Syslifters/sysreptor/releases/tag/2025.50
