### ISSUE TITLE
Websocket Desync/Timeout results in losing writing progress

### ISSUE THREAD

**Issue by greyfenrisulfr** [Syslifters/sysreptor#257] opened 2024-05-23 12:14 UTC
Hello,
After updating to version 2024.40, my colleagues and I noticed that we often lose the web socket connection during reporting.
This results in also losing progress in findings(sometimes whole lines, sometimes only words) as the server sends out the last full version of a finding.

We reproduced it by "fast typing" nonsense into a finding; after a few lines, the connection stalls and gets resetted.
This is only the fast way of reproducing; it also happens now and then on normal reporting.
According to the logs, it's always a DISCONNECT event, followed by an exception. As shown in the screenshot below.
 
![image](https://github.com/Syslifters/sysreptor/assets/26502569/7c6edf1c-1a8c-4ff3-ac16-64ad600199f8)

Also the client console shows the following message.

![image](https://github.com/Syslifters/sysreptor/assets/26502569/650de773-36ef-43ad-a712-c3e2d680879f)

Our setup is a dockerized installation with a nginx reverse proxy.

**Comment by MWedl** [comment] 2024-05-23 13:48
Hi, thanks for reporting. We are already working on a fix because other users also encountered this problem.

The exception in the backend is quite easy to fix.

The frontend timeout is trickier. We could reliably reproduce the timeout by overwhelming the browser (e.g. typing very fast, holding backspace key). The browser is then busy and can no longer process websocket messages in time, thus exceeding the timeout. The root cause of the hang is that propagating text updates to reactive data structures is costly/slow. When there are many updates per second, the browser hangs. We try to improve the performance of update event handling (maybe throtteling and applying them in batches works better).

**Comment by MWedl** [comment] 2024-05-27 07:12
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.43

**Closed by MWedl** 2024-05-27 07:12 UTC
